security:
  oauth2:
    client:
      client-id: pig
      client-secret: pig
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/metadata?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /user/info/*
    - /log/**
    - /**/**
    - /*
#WebService接口地址
webService:
  mdmUrl: http://192.168.0.21:5012/Service/Service.asmx?wsdl


index:
  data:
    db-type: "gp"
    ip-addr: "192.168.0.113"
    port: "5432"
    username: "gpadmin"
    password: "gpadmin"
    database: "cdr"
    cron: 0 30 0 * * ? #晚上12.30执行一次

Etl:
  httpclient:
    data_type: "get" #get post
    data_url: "http://192.168.0.111:7072/clinbrain/api/etl/module"
#    data_url: "http://localhost:9999/MetadataManage/technologyEtl/show"
  data:
    jobId: 74
    hostCode: "001"