security:
  oauth2:
    client:
      client-id: pig
      client-secret: pig
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 865151
    url: jdbc:mysql://localhost:3306/strategy?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /user/info/*
    - /log/**
    - /**/**
    - /*
    - /ruleInfo/**
    - /strategyInfo/**

LabelPool:
  data:
    url: "http://localhost:9999/strategy/labelPool/pages"

